# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FatBoss' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FatBoss
  pod 'SkyFloatingLabelTextField'
  pod 'Locksmith'
  pod 'RealmSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
end
